### variables
PORT = 3000

### testing the server
GET http://localhost:3000

############# AUTH #############

### user registration
POST http://localhost:3000/auth/register
content-type: application/json

{
    "name":"client",
    "email":"client@email.com",
    "password":"123456"
}



### user login
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email":"client@email.com",
    "password":"123456"
}



############# PRODUCTS #############

### add/create product
POST http://localhost:3000/product/add
content-type: application/json

{
    "SKU": "06-59643618",
    "name": "Vans Ward Black Sneaker",
    "description": "A sturdy rubber outsole offers dependable traction. Made with a series of recycled materials, this upper features at least 50% recycled content. ",
    "image": "https://thefoschini.vtexassets.com/arquivos/ids/108588583-1200-1200?v=638425587132100000&width=1200&height=1200&aspect=true",
    "size": [3, 4, 7, 8],
    "stock": 50,
    "price": 1000
}



### view all products
GET http://localhost:3000/product/all



### view one product
GET http://localhost:3000/product/one/65ca01aa075f2dff7d3f4118



### update a product
PUT http://localhost:3000/product/update/65ca01aa075f2dff7d3f4118
content-type: application/json

{
    "size": [3, 4, 6, 7, 8],
    "stock": 10
}



### delete a product
DELETE http://localhost:3000/product/remove/65ca0202075f2dff7d3f411b
